<?php
$g_arrLocalizations_ = array(
	'sp_1' => 'Metal Mine',
	'sp_2' => 'Crystal Mine',
	'sp_3' => 'Deuterium Synthesizer',
	'sp_4' => 'Solar Plant',
	'sp_12' => 'Fusion Reactor',
	'sp_14' => 'Robotics Factory',
	'sp_15' => 'Nanite Factory',
	'sp_21' => 'Shipyard',
	'sp_22' => 'Metal Storage',
	'sp_23' => 'Crystal Storage',
	'sp_24' => 'Deuterium Tank',
	'sp_25' => 'Shielded Metal Den',
	'sp_26' => 'Underground Crystal Den',
	'sp_27' => 'Seabed Deuterium Den',
	'sp_31' => 'Research Lab',
	'sp_33' => 'Terraformer',
	'sp_34' => 'Alliance Depot',
	'sp_41' => 'Lunar Base',
	'sp_42' => 'Sensor Phalanx',
	'sp_43' => 'Jump Gate',
	'sp_44' => 'Missile Silo',
	'sp_106' => 'Espionage Technology',
	'sp_108' => 'Computer Technology',
	'sp_109' => 'Weapons Technology',
	'sp_110' => 'Shielding Technology',
	'sp_111' => 'Armour Technology',
	'sp_113' => 'Energy Technology',
	'sp_114' => 'Hyperspace Technology',
	'sp_115' => 'Combustion Drive',
	'sp_117' => 'Impulse Drive',
	'sp_118' => 'Hyperspace Drive',
	'sp_120' => 'Laser Technology',
	'sp_121' => 'Ion Technology',
	'sp_122' => 'Plasma Technology',
	'sp_123' => 'Intergalactic Research Network',
	'sp_124' => 'Astrophysics',
	'sp_199' => 'Graviton Technology',
	'sp_202' => 'Small Cargo',
	'sp_203' => 'Large Cargo',
	'sp_204' => 'Light Fighter',
	'sp_205' => 'Heavy Fighter',
	'sp_206' => 'Cruiser',
	'sp_207' => 'Battleship',
	'sp_208' => 'Colony Ship',
	'sp_209' => 'Recycler',
	'sp_210' => 'Espionage Probe',
	'sp_211' => 'Bomber',
	'sp_212' => 'Solar Satellite',
	'sp_213' => 'Destroyer',
	'sp_214' => 'Deathstar',
	'sp_215' => 'Battlecruiser',
	'sp_401' => 'Rocket Launcher',
	'sp_402' => 'Light Laser',
	'sp_403' => 'Heavy Laser',
	'sp_404' => 'Gauss Cannon',
	'sp_405' => 'Ion Cannon',
	'sp_406' => 'Plasma Turret',
	'sp_407' => 'Small Shield Dome',
	'sp_408' => 'Large Shield Dome',
	'sp_502' => 'Anti-Ballistic Missiles',
	'sp_503' => 'Interplanetary Missiles',
	'202' => 'S. Cargo',
	'203' => 'L. Cargo',
	'204' => 'L. Fighter',
	'205' => 'H. Fighter',
	'206' => 'Cruiser',
	'207' => 'Battleship',
	'208' => 'Col. Ship',
	'209' => 'Recycler',
	'210' => 'Esp. Probe',
	'211' => 'Bomber',
	'212' => 'S. Sat.',
	'213' => 'Destroyer',
	'214' => 'Deathstar',
	'215' => 'Battlecruiser',
	'401' => 'Roc. Laun.',
	'402' => 'L. Laser',
	'403' => 'H. Laser',
	'404' => 'Gauss',
	'405' => 'Ion Cannon',
	'406' => 'Plasma Turret',
	'407' => 'SSD',
	'408' => 'LSD',
	'menu_main' => 'Начало',
	'menu_account' => '<font size=-2>Моите доклади<font>',
	'account_1' => 'Моите',
	'account_2' => 'доклади',
	'menu_public' => '<font size="-2">Общ. доклади<font>',
	'public_1' => 'Общодостъпни',
	'public_2' => 'доклади',
	'space_dock' => 'SPACE DOCK',
	'menu_search' => 'Search',
	'public_week' => 'week',
	'public_year' => 'year',
	'public_all_time' => 'all time',
	'war1' => 'The',
	'war2' => 'War',
	'add_war1' => 'Add',
	'add_war2' => 'War',
	'domain' => 'Domain',
	'uni' => 'Uni',
	'all' => 'Alliance',
	'profit_alliance' => 'Profit Alliance',
	'losses_alliance' => 'Losses Alliance ',
	'menu_info' => 'Информация',
	'menu_plugin' => 'Допълнения',
	'logserver_title' => 'LogServer - съхранение на доклади от битки от OGame',
	'expand_instruction' => 'Показване на инструкциите за употреба',
	'for_uploading_title' => 'За да добавите нов доклад от битка',
	'for_uploading_step_1' => 'Натиснете десния бутон на мишката докато разглеждате доклада от битката',
	'for_uploading_step_2' => 'Изберете "Veiw HTML-code" (Internet Explorer) или "View Page Source" (Firefox) от контекстното меню, което ще се появи',
	'for_uploading_step_3' => 'Маркирайте целия текст (Ctrl-A), копирайте го (Ctrl-C) и го сложете (Ctrl-V) в полето "Докад от битката (HTML)"',
	'html_report' => 'Доклад от битката (CR-code)',
	'recycler_report' => 'Доклад(и) от рециклиране',
	'comment' => 'Коментари',
	'public_log' => 'Общодостъпен доклад',
	'hide_coords' => 'Скриване на координатите',
	'hide_techs' => 'Скриване на технологиите',
	'hide_time' => 'Скриване на времето',
	'comments' => 'Забрана за коментари',
	'upload' => 'Добавяне',
	'submit' => 'Изпращане',
	'noscript' => 'Броузерът Ви не поддържа скриптове. Но не се безпокойте! Просто използвайте бутона "Submit" и се забавлявайте',
	'upload_err' => 'Добавеният доклад беше изпратен автоматично на разработчиците',
	'errors_occured' => 'Възникнаха грешки',
	'return_to_main' => 'Връщане към главната страница',
	'navigate' => 'Отваряне с броузера',
	'log_uploaded' => 'Докладът беше изпратен успешно',
	'clean_up' => 'Зачистване на планета',
	'title_clean_ap' => 'The attacker has won the battle! He captured',
	'faq_xml' => '
			<title>Какво е LogServer?</title>
				<text>LogServer е мрежов ресурс за обработка, съхраняване и показване на доклади от битките в он-лайн играта "OGame"</text>
			<title>Кои сървери се поддържат?</title>

				<text>Поддържат се всички официални сървери</text>
			<title>Кои версии на играта се поддържат?</title>
				<text>LogServer може да обработва доклади както от сърверите, използващи новия дизайн (v1.x), така и от тези, използващи стария (v0.x)</text>
			<title>Кои езици се поддържат?</title>
				<text>Поддържат се всички езици. LogServer не зависи от езика на докладите. Основният език, използван от самия LogServer е английски</text>
				<text>Ако искате да виждате главната страница на родния си език, моля свържете се с нас и ние заедно ще разрешим проблема</text>
			<title>Какво е значението на разните опции и всичките ли са необходими?</title>
				<text>> <u>"Доклад от битката (HTML)"</u> (необходим) използва се за въвеждането на HTML кода на доклада от битката. За повече информация, вижте "инструкциите за употреба"</text>
				<text>> <u>"Доклад(и) от рециклиране"</u> (незадължителни) използва се за въвеждане на докладите от рециклирането (не HTML, просто обикновен текст)</text>
				<text>Sample 1: "Переработчики в количестве X штук обладают общей грузоподъёмностью в X. Поле обломков содержит X металла и X кристалла. Добыто X металла и X кристалла."</text>
				<text>Sample 2: "Поле обломков содержит X металла и X кристалла. Добыто X металла и X кристалла."</text>
				<text>> <u>"Коментари"</u> (незадължителни) използва се за въвеждане на коментари на играча</text>
				<text>> <u>"Зачистване на планетата"</u> (незадължително) използва се за въвеждане на допълнителна иформациа за ферменето на същата планета (не HTML, просто обикновен текст)</text>
				<text>Например: "Нападателят спечели битката! Той заграби X метал, X кристал и X деутериум."</text>
				<text>> <u>"Общодостъпен доклад"</u> - ако това бъде избрано, докладът Ви ще бъде общодостъпен. Всеки потребител може да извършва търсене в списъка общодостъпни доклади</text>
				<text>> <u>"Скриване на координатите"</u> - ако това бъде избрано, координатите в доклада ще бъдат заместени с "X:X:X"</text>
				<text>> <u>"Скриване на технологиите"</u> - ако това бъде избрано, технологиите в доклада ще бъдат заместени с "X% X% X%"</text>
			<title>Как да се свържете с нас?</title>
				<text>Можете да използвате нашия форум или да изпратите съобщение по електронната поща на адрес w4lifedemon@gmail.com</text>
			',
	'init_str_b' => 'Начална структура',
	'end_str_b' => 'Крайна структура',
	'losses_b' => 'Структурни загуби',
	'expand_all_rounds_title' => 'РАЗГРЪЩАНЕ НА ВСИЧКИ РУНДОВЕ',
	'fleet_statistics_title' => 'КРАЕН РЕЗУЛТАТ ОТ БОЯ',
	'recycler_report_title' => 'ДОКЛАД ОТ РЕЦИКЛИРАНЕТО',
	'total_recycled' => 'Общо рециклирано',
	'total_cleanup' => 'Общо заграбено',
	'metal_r' => 'Метал',
	'and_r' => 'и',
	'crystal_r' => 'кристали',
	'deuterium_r' => 'деутериум',
	'comment_title' => 'КОМЕНТАР',
	'рonor_points' => 'HONOR POINTS',
	'planet_cleanup_title' => 'ЗАЧИСТВАНЕ НА ПЛАНЕТАТА',
	'compounds_title' => 'ОБЩА СТРУКТУРА',
	'att_total_comp' => 'Обща структура на нападателя',
	'def_total_comp' => 'Обща структура на защитника',
	'attacker' => 'Нападател',
	'defender' => 'Защитник',
	'losses_title' => 'ЗАГУБИ',
	'att_total_losses' => 'Общи загуби на нападателя',
	'def_total_losses' => 'Общи загуби на защитника',
	'profit_title' => 'ПЕЧАЛБА',
	'att_gains_1' => 'Нападателят печели',
	'def_gains_1' => 'Защитникът печели',
	'att_gains_2' => 'Нападателят печели',
	'def_gains_2' => 'Защитникът печели',
	'rs_title' => 'СТАТИСТИКА НА РЕСУРСИТЕ',
	'metal' => 'Метал',
	'crystal' => 'Кристали',
	'deuterium' => 'Деутериум',
	'summary' => 'Общо',
	'fleet_t' => 'Флот',
	'losses_t' => 'Загуби',
	'recycled_t' => 'Рециклирано',
	'captured_t' => 'Заграбено',
	'wreckage_t' => 'Рециклаж',
	'profit_1_t' => 'Печалба',
	'cleanup_1_t' => 'Зачистване',
	'ipms_1_t' => 'МПР',
	'deut_consumption' => 'Deut. con.',
	'log_rank_title' => 'РАНГ НА ДОКЛАДА',
	'splitup_title' => 'Подялба на печалбата от СБС-Атаката',
	'proportional' => 'Пропорционално',
	'equally' => 'Еднакво',
	'plugin_info_xml' => '
			<text>Стъпка 1. Погрижете се броузерът Ви да е Firefox 3.5+; другите броузери не се поддържат</text>
			<text>Стъпка 2. Посетете <url_greasemonkey />, свалете и инсталирайте плъгина Greasemonkey</text>
			<text>Стъпка 3. Свалете и инсталирайте този GreaseMonkey скрипт за LogServer-a <url_logserver_greasemonkey_script /></text>
			',
	'spy_report' => 'Шпионски доклад',
	'calc_ipms' => 'Отчитане на МПР',
	'calc_deut_cons' => 'Изчисляване разхода на гориво',
	'display_alliances' => 'Display alliances',
	'display_top' => 'Display top',
	'hr_field' => 'Поле за докладите от рециклаторите',
	'sample' => 'Пример',
	'leave_astx' => 'Оставете звездичката (*) ако всичкият рециклаж е бил прибран',
	'cleanup_field' => 'Поле за докладите от зачистването на планетата',
	'comment_field' => 'Поле за коментари на играча (поддържа се BBcode)',
	'help' => 'Помощ',
	'error' => 'Грешка',
	'info' => 'Информация',
	'warning' => 'Внимание',
	'warning_1' => 'Не е възможно да се определят езика и вселената',
	'warning_2' => 'Причина: клиентският скрипт не можа да намери оригиналния CSS',
	'warning_3' => 'Решение: укажете ги ръчно или сърверът ще използва значения по подразбиране',
	'rec_found' => 'намерен(и) доклад(а)',
	'war_found' => 'war(s) found',
	'most_pop_logs' => 'Най-популявните доклади',
	'most_loss_logs' => 'Трупи с най-голям брой загуби',
	'most_rating_logs' => 'Best rating weekly logs',
	'last' => 'Последните',
	'public_logs' => 'общодостъпни доклади',
	'missle_launch_det' => 'ЗАБЕЛЯЗАНО Е ИЗСТРЕЛВАНЕ НА РАКЕТИ',
	'defense' => 'Защита',
	'fleet' => 'Флот',
	'exp_real_lossed' => 'Очаквани реални загуби',
	'wm_donate' => 'Можете да подкрепите този проект финансово',
	'forgot_password' => 'Забравена парола?',
	'registration' => 'Регистрация',
	'login' => 'Вход',
	'remember_me' => 'Запомняне',
	'fix_list' => 'Списък на промените',
	'thanks' => 'Благодарности',
	'uploaded' => 'Добавено през последните 24 ч.:',
	'total_uploaded' => 'Общо добавено:',
	'search' => 'Търсене',
	'r_users' => 'Регистрирани потребители:',
	'option' => 'Option',
	'setting' => 'Setting',
	'set' => 'Set',
	'default' => 'Default',
	'user_comments_title' => 'КОМЕНТАРИ НА ПОТРЕБИТЕЛИТЕ',
	'index_pagegen' => 'Страницата е генерирана за',
	'index_pagegensec' => 'секунди',
	'com_scpatk' => 'Лом атакера',
	'com_scpdef' => 'Лом дефа',
	'acc_list' => 'Список логов',
	'acc_oldlist' => 'Список старых логов',
	'acc_spyrpt' => 'Шпионские доклады',
	'acc_allog' => 'Логи альтов',
	'page_up' => 'Наверх',
	'uni_features' => 'Universes features',

	'eco' => 'Eco',
	'fleet' => 'Fleet',
	'size' => 'Size',
	'sab' => 'ACB',
	'debris' => 'Debris',
	'ovo' => 'DiDF',
	'top' => 'Top',
	'gamers' => 'Accounts',
	'online' => 'Online',
	'fields' => 'Fields',
	'circular_gal' => 'Circ&#x202F;Galaxies',
	'circular_sys' => 'Circ&#x202F;Systems',
	'probe' => 'Probe',
	'opening_date' => 'Opening&#x202F;date',

	'esp_rep_from' => 'Espionage report from',
	'player' => 'Player',
	'chance_esp' => 'Chance of counter-espionage',
	'unable_info_esp' => 'We were unable to retrieve any reliable information of this type from the scan.',
	'activity_esp_0' => 'Your espionage does not show abnormalities in the atmosphere of the planet. There appears to have been no activity on the planet within the last hour.',
	'activity_esp_1' => 'Your espionage report shows abnormalities in the atmosphere of the planet which suggests activity within the last <font color=\'red\'>%min%</font> minutes.',

	'resources' => 'Resources',
	'fleets' => 'Fleets',
	'defence' => 'Defence',
	'building' => 'Building',
	'research' => 'Research',		
);
