<?php
$g_arrLocalizations_ = array(
	'sp_1' => 'Metallmine',
	'sp_2' => 'Kristallmine',
	'sp_3' => 'Deuterium-Synthetisierer',
	'sp_4' => 'Solarkraftwerk',
	'sp_12' => 'Fusionskraftwerk',
	'sp_14' => 'Roboterfabrik',
	'sp_15' => 'Nanitenfabrik',
	'sp_21' => 'Raumschiffswerft',
	'sp_22' => 'Metallspeicher',
	'sp_23' => 'Kristallspeicher',
	'sp_24' => 'Deuteriumtank',
	'sp_25' => 'Abgeschirmtes Metallversteck',
	'sp_26' => 'Unterirdisches Kristallversteck',
	'sp_27' => 'Meeresgrund-Deuteriumversteck',
	'sp_31' => 'Forschungslabor',
	'sp_33' => 'Terraformer',
	'sp_34' => 'Allianzdepot',
	'sp_41' => 'Mondbasis',
	'sp_42' => 'Sensorphalanx',
	'sp_43' => 'Sprungtor',
	'sp_44' => 'Raketensilo',
	'sp_106' => 'Spionagetechnik',
	'sp_108' => 'Computertechnik',
	'sp_109' => 'Waffentechnik',
	'sp_110' => 'Schildtechnik',
	'sp_111' => 'Raumschiffpanzerung',
	'sp_113' => 'Energietechnik',
	'sp_114' => 'Hyperraumtechnik',
	'sp_115' => 'Verbrennungstriebwerk',
	'sp_117' => 'Impulstriebwerk',
	'sp_118' => 'Hyperraumantrieb',
	'sp_120' => 'Lasertechnik',
	'sp_121' => 'Ionentechnik',
	'sp_122' => 'Plasmatechnik',
	'sp_123' => 'Intergalaktisches Forschungsnetzwerk',
	'sp_124' => 'Astrophysik',
	'sp_199' => 'Gravitonforschung',
	'sp_202' => 'Kleiner Transporter',
	'sp_203' => 'Großer Transporter',
	'sp_204' => 'Leichter Jäger',
	'sp_205' => 'Schwerer Jäger',
	'sp_206' => 'Kreuzer',
	'sp_207' => 'Schlachtschiff',
	'sp_208' => 'Kolonieschiff',
	'sp_209' => 'Recycler',
	'sp_210' => 'Spionagesonde',
	'sp_211' => 'Bomber',
	'sp_212' => 'Solarsatellit',
	'sp_213' => 'Zerstörer',
	'sp_214' => 'Todesstern',
	'sp_215' => 'Schlachtkreuzer',
	'sp_401' => 'Raketenwerfer',
	'sp_402' => 'Leichtes Lasergeschütz',
	'sp_403' => 'Schweres Lasergeschütz',
	'sp_404' => 'Gaußkanone',
	'sp_405' => 'Ionengeschütz',
	'sp_406' => 'Plasmawerfer',
	'sp_407' => 'Kleine Schildkuppel',
	'sp_408' => 'Große Schildkuppel',
	'sp_502' => 'Abfangrakete',
	'sp_503' => 'Interplanetarrakete',
	'202' => 'S. Cargo',
	'203' => 'L. Cargo',
	'204' => 'L. Fighter',
	'205' => 'H. Fighter',
	'206' => 'Cruiser',
	'207' => 'Battleship',
	'208' => 'Col. Ship',
	'209' => 'Recycler',
	'210' => 'Esp. Probe',
	'211' => 'Bomber',
	'212' => 'S. Sat.',
	'213' => 'Destroyer',
	'214' => 'Deathstar',
	'215' => 'Battlecruiser',
	'401' => 'Roc. Laun.',
	'402' => 'L. Laser',
	'403' => 'H. Laser',
	'404' => 'Gauss',
	'405' => 'Ion Cannon',
	'406' => 'Plasma Turret',
	'407' => 'SSD',
	'408' => 'LSD',
	'menu_main' => 'Hauptseite',
	'menu_account' => 'Mein account',
	'account_1' => 'Mein',
	'account_2' => 'account',
	'menu_public' => 'Alle Berichte',
	'public_1' => 'Alle',
	'public_2' => 'Berichte',
	'space_dock' => 'SPACE DOCK',
	'menu_search' => 'Search',
	'public_week' => 'week',
	'public_year' => 'year',
	'public_all_time' => 'all time',
	'war1' => 'The',
	'war2' => 'War',
	'add_war1' => 'Add',
	'add_war2' => 'War',
	'domain' => 'Domain',
	'uni' => 'Uni',
	'all' => 'Alliance',
	'profit_alliance' => 'Profit Alliance',
	'losses_alliance' => 'Losses Alliance ',
	'menu_info' => 'Information',
	'menu_plugin' => 'Plugins',
	'logserver_title' => 'LogServer - Online-Speicher fur Kampfberichte aus OGame',
	'expand_instruction' => 'Benutzungsanleitung ausklappen',
	'for_uploading_title' => 'Zum Hochladen eines neues Berichts',
	'for_uploading_step_1' => 'Drucken Sie die rechten Maustaste auf dem Kampfbericht',
	'for_uploading_step_2' => 'Wahlen Sie den Punkt "Quelltext" (Internet Explorer) oder "Seitenquelltext anzeigen" (Firefox)',
	'for_uploading_step_3' => 'Kopieren sie den Quelltext vollstandig in das Feld "Kampfbericht(HTML-Quelltext)"',
	'html_report' => 'Kampfbericht(CR-code)',
	'recycler_report' => 'Schurfbericht',
	'comment' => 'Kommentar',
	'public_log' => 'Offentlicher Bericht',
	'hide_coords' => 'Verstecke Koordinaten',
	'hide_techs' => 'Verstecke Techniken',
	'hide_time' => 'Verstecke Zeit',
	'comments' => 'Kommentare verbieten',
	'upload' => 'Hochladen',
	'submit' => 'Absenden',
	'noscript' => 'Ihr Browser unterstutzt keine Scripts! Aber keine Panik! Verwenden Sie einfach den Knopf "Absenden" und seien Sie glucklich',
	'upload_err' => 'Gesendetes Objekt wurde automatisch den Entwicklern zugesandt',
	'errors_occured' => 'Es sind Fehler aufgetreten',
	'return_to_main' => 'Auf die Hauptseite zuruckkehren',
	'navigate' => 'Ubergehen',
	'log_uploaded' => 'Bericht wurde erfolgreich ubertragen',
	'clean_up' => 'Die Reinigung des Planeten',
	'title_clean_ap' => 'The attacker has won the battle! He captured',
	'faq_xml' => '<title>Was ist LogServer?</title>

			<text> LogServer - die Ressource fur das Hochladen, Archivieren und Weitergeben der Kampfvortrage aus dem Onlinespiel "OGame"</text>
			<title> Welche Universen werden unterstutzt?</title>
				<text> Alle offiziellen Universen von OGame</text>
			<title> Welche Versionen des Spiels werden unterstutzt?</title>
				<text> LogServer kann sowohl alle Berichte von den Servern verwalten, die mit der neuen Version laufen (ab 1.x, aka "Redesign"), als auch mit der alten Version (0.x).</text>
			<title> Mit welchen Sprachen kann der Berichtearchiv umgehen?</title>
				<text> Es werden alle Sprachen unterstutzt, LogServer hangt nicht von der Sprache des Spiels ab. Die Hauptsprache, die in LogServer verwendet wird, ist Englisch</text>
				<text> Wenn Sie jedoch Ihre Sprache auf der Hauptseite sehen wollen, setzen Sie sich mit uns in Verbindung und wir werden dieses Problem angehen.</text>
			<title> Was  bedeuten all die Bedienelemente auf der Hauptseite? Sind alle unbedingt auszufullen?</title>
				<text>> <u>"Kampfbericht(HTML-Quelltext)"</u> (Pflichtfeld) ist fur die Speicherung des Kampfberichts notwendig. Fur weitere Informationen schauen Sie die Benutzungsanleitung an.</text>
				<text>> <u>"Schurfberichte"</u> (optional) Erganzung des kampfberichts mit (erfolgreichen) Schurfberichten. Hier wird einfacher Text erwartet, kein HTML-Quellcode.</text>
				<text>Beispiel: "Deine 5 Recycler haben eine Gesamtladekapazitat von 100000. Auf dem Ziel treiben 63281 Metall und 38081 Kristall im Raum. Du hast 61918 Metall und 38081 Kristall abgebaut."</text>
				<text>> <u>"Kommentar"</u> (optional) Fur Ihren eigenen Kommentar unter dem Kampfbericht</text>
				<text>> <u>"Die Reinigung des Planeten"</u> (optional) Erganzt den Bericht um Ergebnisse der der nachfolgenden Angriffe auf denselben Planeten, wo (nur) Ressourcen erbeutet werden (einfacher Text, kein HTML-Quellcode).</text>
				<text> Beispiel: "Der Angreifer hat die Schlacht gewonnen. Er erbeutet xxx Metall, yyy Kristall und zzz Deuterium."</text>
				<text>> <u>"Offentlicher Bericht"</u> - wenn aktiviert, wird der Bericht der offentlich zuganglichen Liste hinzugefugt. Alle Besucher konnen diese Liste einsehen.</text>
				<text>> <u>"Verstecke Koordinaten"</u> - Koordinaten werden mit "X:X:X" verborgen.</text>
				<text>> <u>"Verstecke Techniken"</u> - die Techniken des Angreifers und des Verteiigers werden mit "Х % Х % Х %" verborgen.</text>
			<title> Wie kann man sich mit uns verbinden?</title>
				<text> Sie konnen unser Forum benutzen oder sich per e-mail an die Adresse w4lifedemon@gmail.com wenden.</text>
			',
	'init_str_b' => 'Die Anfangsstruktur',
	'end_str_b' => 'Die endliche Struktur',
	'losses_b' => 'Die Verluste der Struktur',
	'expand_all_rounds_title' => 'ALLE RUNDEN ZEIGEN',
	'fleet_statistics_title' => 'DIE FLOTTEN-STATISTIK',
	'recycler_report_title' => 'SCHURFBERICHT',
	'total_recycled' => 'Insgesamt abgebaut',
	'total_cleanup' => 'Insgesamt erbeutet',
	'metal_r' => 'Metall ',
	'and_r' => 'und',
	'crystal_r' => 'Kristall',
	'deuterium_r' => 'Deuterium',
	'comment_title' => 'KOMMENTAR',
	'рonor_points' => 'HONOR POINTS',
	'planet_cleanup_title' => 'DIE REINIGUNG DES PLANETEN',
	'compounds_title' => 'DER WERT DER FLOTTE (DER VERTEIDIGUNG)',
	'att_total_comp' => 'Des Angreifers',
	'def_total_comp' => 'Des Verteidigers',
	'attacker' => 'Angreifer',
	'defender' => 'Verteidiger',
	'losses_title' => 'VERLUSTE',
	'att_total_losses' => 'Des Angreifers',
	'def_total_losses' => 'Des Verteidigers',
	'profit_title' => 'GEWINN',
	'att_gains_1' => 'Fur den Angreifer',
	'def_gains_1' => 'Fur den Verteidiger',
	'att_gains_2' => 'Fur den Angreifer',
	'def_gains_2' => 'Fur den Verteidiger',
	'rs_title' => 'RESSOURCEN STATISTIK',
	'metal' => 'Metall',
	'crystal' => 'Kristall',
	'deuterium' => 'Deuterium',
	'summary' => 'Insgesamt',
	'fleet_t' => 'Flotte',
	'losses_t' => 'Verluste',
	'recycled_t' => 'Abgebaut',
	'captured_t' => 'Erbeutet',
	'wreckage_t' => 'Trummerfeld',
	'profit_1_t' => 'Gewinn',
	'cleanup_1_t' => 'Clean-up',
	'ipms_1_t' => 'IPRs',
	'deut_consumption' => 'Deut. con.',
	'log_rank_title' => 'DIE EINSCHATZUNG DES BERICHTS',
	'splitup_title' => 'AKS AUFTEILUNG',
	'proportional' => 'Proportional',
	'equally' => 'Gleich',
	'plugin_info_xml' => '
			<text> Schritt 1. Uberzeugen sich, dass bei Ihnen der Browser Firefox der Version 3.5 und alterer ist, andere Browser bis werden unterstutzt</text> 
			<text> Schritt 2. Besuchen Sie <url_greasemonkey />, beladen Sie und stellen Sie plugin Greasemonkey  fest</text>
			<text> Schritt 3. Beladen Sie und stellen Sie LogServer GM script (<url_logserver_greasemonkey_script />) fest</text>
			',
	'spy_report' => 'Spy report',
	'calc_ipms' => 'Calculate IPMs',
	'calc_deut_cons' => 'Calc. deuterium consumption',
	'display_alliances' => 'Display alliances',
	'display_top' => 'Display top',
	'hr_field' => 'Field for harvester report',
	'sample' => 'Sample',
	'leave_astx' => 'Leave asterisk symbol (*) in case of all debris are harvested',
	'cleanup_field' => 'Field for planet clean-up (waves)',
	'comment_field' => 'Field for player comment (BB-code is supported)',
	'help' => 'Help',
	'error' => 'Error',
	'info' => 'Information',
	'warning' => 'Warning',
	'warning_1' => 'Universe and domain automatic detect is impossible',
	'warning_2' => 'Reason: client script was not able to detect native CSS',
	'warning_3' => 'Solution: select it manually or server will apply default values',
	'rec_found' => 'record(s) found',
	'war_found' => 'war(s) found',
	'most_pop_logs' => 'Most popular logs',
	'most_loss_logs' => 'Stämme mit der größten Anzahl von Verlusten',
	'most_rating_logs' => 'Best rating weekly logs',
	'last' => 'Last',
	'public_logs' => 'public logs',
	'missle_launch_det' => 'MISSLES LAUNCH DETECTED',
	'defense' => 'Defense',
	'fleet' => 'Fleet',
	'exp_real_lossed' => 'Expected real losses',
	'wm_donate' => 'You can support this project financially',
	'forgot_password' => 'Passwort vergessen?',
	'registration' => 'Registrieren',
	'login' => 'Anmelden',
	'remember_me' => 'Eingeloggt bleiben',
	'fix_list' => 'Fixes',
	'thanks' => 'Danke',
	'uploaded' => 'Hochgeladen in 24h:',
	'total_uploaded' => 'Insgesamt hochgeladen:',
	'search' => 'Suchen',
	'r_users' => 'Registrierte Benutzer:',
	'option' => 'Option',
	'setting' => 'Setting',
	'set' => 'Set',
	'default' => 'Default',
	'user_comments_title' => 'USER COMMENTS',
	'index_pagegen' => 'Seite generiert in',
	'index_pagegensec' => 'Sekunden',
	'com_scpatk' => 'Scrap Attacker',
	'com_scpdef' => 'scrap Defender',
	'acc_list' => 'Liste der logs',
	'acc_oldlist' => 'Liste der alten Protokolle',
	'acc_spyrpt' => 'Spy Berichte',
	'acc_allog' => 'Alle Logs',
	'page_up' => 'nach oben',
	'uni_features' => 'Universes features',

	'eco' => 'Eco',
	'fleet' => 'Fleet',
	'size' => 'Size',
	'sab' => 'ACB',
	'debris' => 'Debris',
	'ovo' => 'DiDF',
	'top' => 'Top',
	'gamers' => 'Gamers',
	'online' => 'Online',
	'fields' => 'Fields',
	'circular_gal' => 'Circ&#x202F;Galaxies',
	'circular_sys' => 'Circ&#x202F;Systems',
	'probe' => 'Probe',
	'opening_date' => 'Opening&#x202F;date',

	'esp_rep_from' => 'Espionage report from',
	'player' => 'Player',
	'chance_esp' => 'Chance of counter-espionage',
	'unable_info_esp' => 'We were unable to retrieve any reliable information of this type from the scan.',
	'activity_esp_0' => 'Your espionage does not show abnormalities in the atmosphere of the planet. There appears to have been no activity on the planet within the last hour.',
	'activity_esp_1' => 'Your espionage report shows abnormalities in the atmosphere of the planet which suggests activity within the last <font color=\'red\'>%min%</font> minutes.',

	'resources' => 'Resources',
	'fleets' => 'Fleets',
	'defence' => 'Defence',
	'building' => 'Building',
	'research' => 'Research',		
);
