<?php
$g_arrLocalizations_ = array(
	'sp_1' => 'Metal Mine',
	'sp_2' => 'Crystal Mine',
	'sp_3' => 'Deuterium Synthesizer',
	'sp_4' => 'Solar Plant',
	'sp_12' => 'Fusion Reactor',
	'sp_14' => 'Robotics Factory',
	'sp_15' => 'Nanite Factory',
	'sp_21' => 'Shipyard',
	'sp_22' => 'Metal Storage',
	'sp_23' => 'Crystal Storage',
	'sp_24' => 'Deuterium Tank',
	'sp_25' => 'Shielded Metal Den',
	'sp_26' => 'Underground Crystal Den',
	'sp_27' => 'Seabed Deuterium Den',
	'sp_31' => 'Research Lab',
	'sp_33' => 'Terraformer',
	'sp_34' => 'Alliance Depot',
	'sp_41' => 'Lunar Base',
	'sp_42' => 'Sensor Phalanx',
	'sp_43' => 'Jump Gate',
	'sp_44' => 'Missile Silo',
	'sp_106' => 'Espionage Technology',
	'sp_108' => 'Computer Technology',
	'sp_109' => 'Weapons Technology',
	'sp_110' => 'Shielding Technology',
	'sp_111' => 'Armour Technology',
	'sp_113' => 'Energy Technology',
	'sp_114' => 'Hyperspace Technology',
	'sp_115' => 'Combustion Drive',
	'sp_117' => 'Impulse Drive',
	'sp_118' => 'Hyperspace Drive',
	'sp_120' => 'Laser Technology',
	'sp_121' => 'Ion Technology',
	'sp_122' => 'Plasma Technology',
	'sp_123' => 'Intergalactic Research Network',
	'sp_124' => 'Astrophysics',
	'sp_199' => 'Graviton Technology',
	'sp_202' => 'Small Cargo',
	'sp_203' => 'Large Cargo',
	'sp_204' => 'Light Fighter',
	'sp_205' => 'Heavy Fighter',
	'sp_206' => 'Cruiser',
	'sp_207' => 'Battleship',
	'sp_208' => 'Colony Ship',
	'sp_209' => 'Recycler',
	'sp_210' => 'Espionage Probe',
	'sp_211' => 'Bomber',
	'sp_212' => 'Solar Satellite',
	'sp_213' => 'Destroyer',
	'sp_214' => 'Deathstar',
	'sp_215' => 'Battlecruiser',

	'sp_217' => 'Crawler',
	'sp_218' => 'Reaper',
	'sp_219' => 'Pathfinder',

	'sp_401' => 'Rocket Launcher',
	'sp_402' => 'Light Laser',
	'sp_403' => 'Heavy Laser',
	'sp_404' => 'Gauss Cannon',
	'sp_405' => 'Ion Cannon',
	'sp_406' => 'Plasma Turret',
	'sp_407' => 'Small Shield Dome',
	'sp_408' => 'Large Shield Dome',
	'sp_502' => 'Anti-Ballistic Missiles',
	'sp_503' => 'Interplanetary Missiles',
	'202' => 'S. Cargo',
	'203' => 'L. Cargo',
	'204' => 'L. Fighter',
	'205' => 'H. Fighter',
	'206' => 'Cruiser',
	'207' => 'Battleship',
	'208' => 'Col. Ship',
	'209' => 'Recycler',
	'210' => 'Esp. Probe',
	'211' => 'Bomber',
	'212' => 'S. Sat.',
	'213' => 'Destroyer',
	'214' => 'Deathstar',
	'215' => 'Battlecruiser',

	'217' => 'Crawler',
	'218' => 'Reaper',
	'219' => 'Pathfinder',

	'401' => 'Roc. Laun.',
	'402' => 'L. Laser',
	'403' => 'H. Laser',
	'404' => 'Gauss',
	'405' => 'Ion Cannon',
	'406' => 'Plasma Turret',
	'407' => 'SSD',
	'408' => 'LSD',
	'menu_main' => 'Main page',
	'menu_account' => 'My account',
	'account_1' => 'My',
	'account_2' => 'account',
	'menu_public' => 'Public list',
	'public_1' => 'Public',
	'public_2' => 'list',
	'space_dock' => 'SPACE DOCK',
	'menu_search' => 'Search',
	'public_week' => 'week',
	'public_year' => 'year',
	'public_all_time' => 'all time',
	'war1' => 'The',
	'war2' => 'War',
	'add_war1' => 'Add',
	'add_war2' => 'War',
	'domain' => 'Domain',
	'uni' => 'Uni',
	'all' => 'Alliance',
	'profit_alliance' => 'Profit Alliance',
	'losses_alliance' => 'Losses Alliance ',
	'menu_info' => 'Information',
	'menu_plugin' => 'Plugins',
	'logserver_title' => 'LogServer - storage of combat reports from OGame',
	'expand_instruction' => 'Expand usage instruction down',
	'for_uploading_title' => 'For uploading new log',
	'for_uploading_step_1' => 'Press the right mouse button while viewing your combat report',
	'for_uploading_step_2' => 'Choose "View HTML-code" (Internet Explorer) or "View Page Source" (Firefox)',
	'for_uploading_step_3' => 'Select the entire text (Ctrl-A), copy it (Ctrl-C) and paste it (Ctrl-V) into field "Combat report (HTML-code)"',
	'html_report' => 'Combat report (CR-code)',
	'recycler_report' => 'Recycler report',
	'comment' => 'Comment',
	'public_log' => 'Public log',
	'hide_coords' => 'Hide coordinates',
	'hide_techs' => 'Hide technologies',
	'hide_time' => 'Hide Time',
	'comments' => 'Ban comments',
	'upload' => 'Upload',
	'submit' => 'Submit',
	'noscript' => 'Your browser doesn\'t support scripts! But don\'t worry! Just use the button "Submit" and be happy',
	'upload_err' => 'Uploaded object was automatically sent to the developers',
	'errors_occured' => 'Errors occured',
	'return_to_main' => 'Return to the main page',
	'navigate' => 'Navigate',
	'log_uploaded' => 'Log successfully uploaded',
	'clean_up' => 'Planet clean-up',
	'title_clean_ap' => 'The attacker has won the battle! He captured',
	'faq_xml' => '
		 	<title>What is LogServer?</title>
		 		<text>LogServer is a network resource used for processing, storing and displaying combat reports for the on-line game "OGame"</text>
		 	<title>Which servers are supported?</title>
		 		<text>All official servers are supported</text>
		 	<title>Which game versions are supported?</title>
		 		<text>LogServer can process reports from servers using the new engine (v1.x, a.k.a. "redesign") or the old engine (v0.x)</text>
		 	<title>Which languages are supported?</title>
		 		<text>All languages are supported and LogServer is independent of the game localization. The language used by LogServer is English</text>
		 		<text>If you want to see the main page in your own language, please contact us and we will work on it together</text>
		 	<title>What is the meaning of all controls on the main page and are all of them required?</title>
		 		<text>> <u>"Combat report (HTML-code)"</u> (required) used for entering the HTML-code of your battle report. See "usage instruction" to get more info</text>
		 		<text>> <u>"Harvesting report"</u> (optional) used for entering the harvesting reports (not HTML, just simple text)</text>
		 		<text>Sample 1: "		Your recycler(s) (Number) have a total cargo capacity of x At the target [x:x:x], x Metal and x Crystal are floating in space. You have harvested x Metal and x Crystal. "</text>
				<text>Sample 2: "Debris field Contained X metal and X crystal. You Mined metal X and X crystal."</text>
				<text>> <u>"Comment"</u> (optional) used for entering player comments</text>
		 		<text>> <u>"Planet clean-up"</u> (optional) used for entering the additional (farming) results for the same planet (not HTML, just simple text)</text>
		 		<text>Sample: "The attacker has won the battle! He captured: X metal, X crystal and X deuterium."</text>
		 		<text>> <u>"Public"</u> - if checked, your log will be added to the public list. All users can perform searches of the public logs</text>
		 		<text>> <u>"Hide coordinates"</u> - if checked, the coordinates will be replaced with "X:X:X"</text>
		 		<text>> <u>"Hide technologies"</u> - if checked, the technologies will be replaced with "X% X% X%"</text>
		 	<title>How to contact us?</title>
		 		<text>You can use our forum or send e-mail to w4lifedemon@gmail.com</text>',
	'init_str_b' => 'Initial structure',
	'end_str_b' => 'End structure',
	'losses_b' => 'Structure losses',
	'expand_all_rounds_title' => 'Expand all rounds',
	'fleet_statistics_title' => 'FLEET STATISTICS',
	'recycler_report_title' => 'RECYCLER REPORT',
	'total_recycled' => 'Total recycled',
	'total_cleanup' => 'Total cleanup',
	'metal_r' => 'metal',
	'and_r' => 'and',
	'crystal_r' => 'crystal',
	'deuterium_r' => 'deuterium',
	'comment_title' => 'COMMENT',
	'рonor_points' => 'HONOR POINTS',
	'planet_cleanup_title' => 'PLANET CLEAN-UP',
	'compounds_title' => 'COMPOUNDS',
	'att_total_comp' => 'Attacker\'s total compound',
	'def_total_comp' => 'Defender\'s total compound',
	'attacker' => 'Attacker',
	'defender' => 'Defender',
	'losses_title' => 'LOSSES',
	'att_total_losses' => 'Attacker\'s total losses',
	'def_total_losses' => 'Defender\'s total losses',
	'profit_title' => 'PROFIT',
	'att_gains_1' => 'Attacker gains',
	'def_gains_1' => 'Defender gains',
	'att_gains_2' => 'Attacker gains',
	'def_gains_2' => 'Defender gains',
	'rs_title' => 'RESOURCES STATISTICS',
	'metal' => 'Metal',
	'crystal' => 'Crystal',
	'deuterium' => 'Deuterium',
	'summary' => 'Total',
	'fleet_t' => 'Fleet',
	'losses_t' => 'Losses',
	'recycled_t' => 'Harvested',
	'captured_t' => 'Captured',
	'wreckage_t' => 'Debris',
	'profit_1_t' => 'Profit',
	'cleanup_1_t' => 'Clean-up',
	'ipms_1_t' => 'IPMs',
	'deut_consumption' => 'Deut. con.',
	'log_rank_title' => 'LOG RANK',
	'splitup_title' => 'SPLIT-UP',
	'proportional' => 'Proportional',
	'equally' => 'Equally',
	'plugin_info_xml' => '
		 	<text>Step 1. Make sure that your browser is Firefox 3.5+, other browsers are not supported</text>
		 	<text>Step 2. Visit <url_greasemonkey />, pour telecharger et installez Greasemonkey</text>
		 	<text>Step 3. Download and install LogServer GM script from here <url_logserver_greasemonkey_script /></text>
		 	',
	'spy_report' => 'Spy report',
	'calc_ipms' => 'Calculate IPMs',
	'calc_deut_cons' => 'Calc. deuterium consumption',
	'display_alliances' => 'Display alliances',
	'display_top' => 'Display top',
	'hr_field' => 'Field for harvester report',
	'sample' => 'Sample',
	'leave_astx' => 'Leave asterisk symbol (*) in case of all debris are harvested',
	'cleanup_field' => 'Field for planet clean-up (waves)',
	'comment_field' => 'Field for player comment (BB-code is supported)',
	'help' => 'Help',
	'error' => 'Error',
	'info' => 'Information',
	'warning' => 'Warning',
	'warning_1' => 'Universe and domain automatic detect is impossible',
	'warning_2' => 'Reason: client script was not able to detect native CSS',
	'warning_3' => 'Solution: select it manually or server will apply default values',
	'rec_found' => 'record(s) found',
	'war_found' => 'war(s) found',
	'most_pop_logs' => 'Most popular logs',
	'most_loss_logs' => 'Logs with the greatest number of losses',
	'most_rating_logs' => 'Best rating weekly logs',
	'last' => 'Last',
	'public_logs' => 'public logs',
	'missle_launch_det' => 'MISSLES LAUNCH DETECTED',
	'defense' => 'Defense',
	'fleet' => 'Fleet',
	'exp_real_lossed' => 'Expected real losses',
	'wm_donate' => 'You can support this project financially',
	'forgot_password' => 'Forgot Password?',
	'registration' => 'Registration',
	'login' => 'Login',
	'remember_me' => 'Remember me',
	'fix_list' => 'Fix list',
	'thanks' => 'Thanks',
	'uploaded' => 'Uploaded in 24h:',
	'total_uploaded' => 'Total uploaded:',
	'search' => 'Search',
	'r_users' => 'Users:',
	'option' => 'Option',
	'setting' => 'Setting',
	'set' => 'Set',
	'default' => 'Default',
	'user_comments_title' => 'USER COMMENTS',
	'index_pagegen' => 'Page Generated In',
	'index_pagegensec' => 'Seconds =)',
	'com_scpatk' => 'Scrap Attacker',
	'com_scpdef' => 'Scrap Defender',
	'acc_list' => 'List of logs',
	'acc_oldlist' => 'List of old logs',
	'acc_spyrpt' => 'Spy reports',
	'acc_allog' => 'All Logs',
	'page_up' => 'UP',
	'uni_features' => 'Universes features',

	'eco' => 'Eco',
	'fleet' => 'Fleet',
	'size' => 'Size',
	'sab' => 'ACB',
	'debris' => 'Debris',
	'ovo' => 'DiDF',
	'top' => 'Top',
	'gamers' => 'Accounts',
	'online' => 'Online',
	'fields' => 'Fields',
	'circular_gal' => 'Circ&#x202F;Galaxies',
	'circular_sys' => 'Circ&#x202F;Systems',
	'probe' => 'Probe',
	'opening_date' => 'Opening&#x202F;date',

	'esp_rep_from' => 'Espionage report from',
	'player' => 'Player',
	'chance_esp' => 'Chance of counter-espionage',
	'unable_info_esp' => 'We were unable to retrieve any reliable information of this type from the scan.',
	'activity_esp_0' => 'Your espionage does not show abnormalities in the atmosphere of the planet. There appears to have been no activity on the planet within the last hour.',
	'activity_esp_1' => 'Your espionage report shows abnormalities in the atmosphere of the planet which suggests activity within the last <font color=\'red\'>%min%</font> minutes.',

	'resources' => 'Resources',
	'fleets' => 'Fleets',
	'defence' => 'Defence',
	'building' => 'Building',
	'research' => 'Research',
);
