<?php
$g_arrLocalizations_ = array(
	'sp_1' => 'Mine de métal',
	'sp_2' => 'Mine de cristal',
	'sp_3' => 'Synthétiseur de deutérium',
	'sp_4' => 'Centrale électrique solaire',
	'sp_12' => 'Centrale électrique de fusion',
	'sp_14' => 'Usine de robots',
	'sp_15' => 'Usine de nanites',
	'sp_21' => 'Chantier spatial',
	'sp_22' => 'Hangar de métal',
	'sp_23' => 'Hangar de cristal',
	'sp_24' => 'Réservoir de deutérium',
	'sp_25' => 'Cachette de métal camouflée',
	'sp_26' => 'Cachette de cristal souterraine',
	'sp_27' => 'Cachette de deutérium sous-marine',
	'sp_31' => 'Laboratoire de recherche',
	'sp_33' => 'Terraformeur',
	'sp_34' => 'Dépôt de ravitaillement',
	'sp_41' => 'Base lunaire',
	'sp_42' => 'Phalange de capteur',
	'sp_43' => 'Porte de saut spatial',
	'sp_44' => 'Silo de missiles',
	'sp_106' => 'Technologie Espionnage',
	'sp_108' => 'Technologie Ordinateur',
	'sp_109' => 'Technologie Armes',
	'sp_110' => 'Technologie Bouclier',
	'sp_111' => 'Technologie Protection des vaisseaux spatiaux',
	'sp_113' => 'Technologie énergétique',
	'sp_114' => 'Technologie hyperespace',
	'sp_115' => 'Réacteur à combustion',
	'sp_117' => 'Réacteur à impulsion',
	'sp_118' => 'Propulsion hyperespace',
	'sp_120' => 'Technologie Laser',
	'sp_121' => 'Technologie à ions',
	'sp_122' => 'Technologie Plasma',
	'sp_123' => 'Réseau de recherche intergalactique',
	'sp_124' => 'Astrophysique',
	'sp_199' => 'Technologie Graviton',
	'sp_202' => 'Petit transporteur',
	'sp_203' => 'Grand transporteur',
	'sp_204' => 'Chasseur léger',
	'sp_205' => 'Chasseur lourd',
	'sp_206' => 'Croiseur',
	'sp_207' => 'Vaisseau de bataille',
	'sp_208' => 'Vaisseau de colonisation',
	'sp_209' => 'Recycleur',
	'sp_210' => 'Sonde d`espionnage',
	'sp_211' => 'Bombardier',
	'sp_212' => 'Satellite solaire',
	'sp_213' => 'Destructeur',
	'sp_214' => 'Étoile de la mort',
	'sp_215' => 'Traqueur',
	'sp_401' => 'Lanceur de missiles',
	'sp_402' => 'Artillerie laser légère',
	'sp_403' => 'Artillerie laser lourde',
	'sp_404' => 'Canon de Gauss',
	'sp_405' => 'Artillerie à ions',
	'sp_406' => 'Lanceur de plasma',
	'sp_407' => 'Petit bouclier',
	'sp_408' => 'Grand bouclier',
	'sp_502' => 'Missile d`interception',
	'sp_503' => 'Missile interplanétaire',
	'202' => 'S. Cargo',
	'203' => 'L. Cargo',
	'204' => 'L. Fighter',
	'205' => 'H. Fighter',
	'206' => 'Cruiser',
	'207' => 'Battleship',
	'208' => 'Col. Ship',
	'209' => 'Recycler',
	'210' => 'Esp. Probe',
	'211' => 'Bomber',
	'212' => 'S. Sat.',
	'213' => 'Destroyer',
	'214' => 'Deathstar',
	'215' => 'Battlecruiser',
	'401' => 'Roc. Laun.',
	'402' => 'L. Laser',
	'403' => 'H. Laser',
	'404' => 'Gauss',
	'405' => 'Ion Cannon',
	'406' => 'Plasma Turret',
	'407' => 'SSD',
	'408' => 'LSD',
	'menu_main' => 'Page d\'accueil',
	'menu_account' => 'Mon compte',
	'account_1' => 'Mon',
	'account_2' => 'compte',
	'menu_public' => 'Liste publique',
	'public_1' => 'Liste',
	'public_2' => 'publique',
	'space_dock' => 'SPACE DOCK',
	'menu_search' => 'Search',
	'public_week' => 'week',
	'public_year' => 'year',
	'public_all_time' => 'all time',
	'war1' => 'The',
	'war2' => 'War',
	'add_war1' => 'Add',
	'add_war2' => 'War',
	'domain' => 'Domain',
	'uni' => 'Uni',
	'all' => 'Alliance',
	'profit_alliance' => 'Profit Alliance',
	'losses_alliance' => 'Losses Alliance ',
	'menu_info' => 'Informations',
	'menu_plugin' => 'Plugins',
	'logserver_title' => 'Logserver - enregistrement des rapports de combats depuis ogame',
	'expand_instruction' => 'Mode d\'emploi',
	'for_uploading_title' => 'Pour enregistrer de nouveaux log',
	'for_uploading_step_1' => 'Faites un clic droit lors du visionnage du rapport de combat',
	'for_uploading_step_2' => 'Choisir "voir le code HTML" (Internet Explorer) ou "voir le code source de la page" (Firefox)',
	'for_uploading_step_3' => 'Selectionner le text au complet (ctrl+A), copiez le (ctrl+C) et colez le (ctrl+V) dans le champs "rapports de combat (code HTML)"',
	'html_report' => 'Rapports de combat (CR-code)',
	'recycler_report' => 'Rapport de recyclage',
	'comment' => 'Commentaires',
	'public_log' => 'Log publiques',
	'hide_coords' => 'Masquer les coordonnees',
	'hide_techs' => 'Masquer les technologies',
	'hide_time' => 'Masquer le temps',
	'comments' => 'Ban commentaires',
	'upload' => 'Envoyer',
	'submit' => 'Soumettre',
	'noscript' => 'Votre navigateur ne supporte pas ce script! mais ne vous inquitte pa! Cliquez sur le boutton "Soumettre" and c\'est bon',
	'upload_err' => 'Les elements enregistres sont automatiquements envoyes aux devellopeurs',
	'errors_occured' => 'Des erreurs se sont produites',
	'return_to_main' => 'Retourner a la page d\'accueil',
	'navigate' => 'Parcourir',
	'log_uploaded' => 'Log enregistres avec succes',
	'clean_up' => 'Infos des planetes',
	'title_clean_ap' => 'The attacker has won the battle! He captured',
	'faq_xml' => '
			<title>Qu\'est ce que Logserver?</title>
		 		<text>Logserver est un systeme de ressource en lignepermettant l\'observation, l\'enregistrement et l\'afichage des rapports de combat du jeu en ligne "OGame"</text>
		 	<title>Quels serveurs sont supportes?</title>
		 		<text>Tout les serveurs officiels le sont</text>
		 	<title>Quelles versions sont supportees?</title>
		 		<text>LogServer peut traiter les serveurs avec le nouveau systeme (v1.x, a.k.a. "redesign") ou l\'ancien systeme(v0.x)</text>
		 	<title>Quelles langues sont supportees?</title>
		 		<text>Toutes les langues sont supporteeset Logserveur est independant a la localisation du jeu. Le langage utilise par Lorserveur est l\'anglais</text>
		 		<text>Si vous voulez voir la pge d\'accueil dans votre propte langue, veuillez nous contacter et nous y travaillerons ensemble</text>
		 	<title>Quelle est la signification des controles sur la page d\'accueil et sont-ils tous obligatoires?</title>
		 		<text>> <u>"Rapport de combat (HTML-code)"</u> (obligatoire) utilise pour l\'enregistrement de vos RC. Voyez "mode d\'emploi" pour plus d\'informations</text>
		 		<text>> <u>"RApprot de recyclage"</u> (optionnel) utilise pour enregistrer les rapports de recyclage (pas de HTML, simple texte)</text>
		 		<text>Exemple 1: "Переработчики в количестве X штук обладают общей грузоподъёмностью в X. Поле обломков содержит X металла и X кристалла. Добыто X металла и X кристалла."</text>
				<text>Exemple 2: "Поле обломков содержит X металла и X кристалла. Добыто X металла и X кристалла."</text>
				<text>> <u>"Commentaires"</u> (optionnel)utilise pour laisser les commentaires des joueurs</text>
		 		<text>> <u>"RAZ planete"</u> (optionnel) utilise pour entrerles resultats suplementaires (production)pour la meme planete (pas de HTML, simple texte)</text>
		 		<text>Exemple: "L\'attaquant a gagne la battaille, il emporte: X metal, X cristal and X deuterium."</text>
		 		<text>> <u>"Publique"</u> - si vous cochez ceci, vos enregistrements seront ajoutes a la liste publique. Tout les joueurs peuvent effectuer une recherche dans les Log publiques</text>
		 		<text>> <u>"Masquer coordonnees"</u> - si vous cochez ceci, les coordonees seront remplacees par: "X:X:X"</text>
		 		<text>> <u>"Masquer technologies"</u> - si vous cochez ceci, les technologies seront remplacees par: "X% X% X%"</text>
		 	<title>Comment nous contacter?</title>
		 		<text>Vous pouvez utiliser le forum, ou nous envoyer un mail a  w4lifedemon@gmail.com</text>',
	'init_str_b' => 'Structure de base',
	'end_str_b' => 'Structure finale',
	'losses_b' => 'Structure perdue',
	'expand_all_rounds_title' => 'Remplacer les rounds',
	'fleet_statistics_title' => 'Statistiques de flotte',
	'recycler_report_title' => 'Rapport de recyclage',
	'total_recycled' => 'Recyclage totaux',
	'total_cleanup' => 'Remise a zero',
	'metal_r' => 'metal',
	'and_r' => 'et',
	'crystal_r' => 'cristal',
	'deuterium_r' => 'deuteriu',
	'comment_title' => 'COMMENTAIRES',
	'рonor_points' => 'HONOR POINTS',
	'planet_cleanup_title' => 'INFOS PLANETE',
	'compounds_title' => 'COMPOSITION',
	'att_total_comp' => 'Composition attaquante totale',
	'def_total_comp' => 'Composition defendante totale',
	'attacker' => 'Attaquant',
	'defender' => 'Defenseur',
	'losses_title' => 'PERTES',
	'att_total_losses' => 'Pertes totales attaquants',
	'def_total_losses' => 'Pertes totales defendeurs',
	'profit_title' => 'PROFITS',
	'att_gains_1' => 'Gains attaquants',
	'def_gains_1' => 'Gain defenseurs',
	'att_gains_2' => 'L\'attaquant gagne',
	'def_gains_2' => 'Дe defendeur gagne',
	'rs_title' => 'Stat des resources',
	'metal' => 'Metal',
	'crystal' => 'Cristal',
	'deuterium' => 'Deuterium',
	'summary' => 'Total',
	'fleet_t' => 'Flotte',
	'losses_t' => 'Pertes',
	'recycled_t' => 'Recyclees',
	'captured_t' => 'Capturees',
	'wreckage_t' => 'Сhamps de debris',
	'profit_1_t' => 'Зrofits',
	'cleanup_1_t' => 'Infos',
	'ipms_1_t' => 'Mips',
	'deut_consumption' => 'Deut. con.',
	'log_rank_title' => 'CLASSEMENT DES LOGS',
	'splitup_title' => 'SPLIT-UP',
	'proportional' => 'Proportions',
	'equally' => 'Correspond a',
	'plugin_info_xml' => '
		 	<text>Step 1. Assurez vous que votre navigateur est Firefox 3.5+, d\'autres navigateurs ne seraient pas supportes</text>
		 	<text>Step 2. Visitez <url_greasemonkey />, download and install Greasemonkey plugin</text>
		 	<text>Step 3. Telechargez et instalez ici le script GM Logserver <url_logserver_greasemonkey_script /></text>
		 	',
	'spy_report' => 'Rapports d\'espionnage',
	'calc_ipms' => 'Calculs des Mips',
	'calc_deut_cons' => 'Calcul de la consomation de deuterium',
	'display_alliances' => 'Display alliances',
	'display_top' => 'Display top',
	'hr_field' => 'Champs de debris du rapport de recyclage',
	'sample' => 'Exemple',
	'leave_astx' => 'Laissez l\'asterix (*) dans les cases des cdr recoltes',
	'cleanup_field' => 'Emplacement des infos planetes (vagues)',
	'comment_field' => 'Emplacement pour les commentaires des joueurs (BB-code est supporte)',
	'help' => 'Aide',
	'error' => 'Erreur',
	'info' => 'Information',
	'warning' => 'Attention',
	'warning_1' => 'Detection automatique de l\'univers impossible',
	'warning_2' => 'Raison: le script n\'a pas ete capable de detecter le CSS',
	'warning_3' => 'Solution: selectionnez le manuellement ou le serveur appliquera les valeurs par defaut',
	'rec_found' => 'Record trouves',
	'war_found' => 'war trouves',
	'most_pop_logs' => 'Logs les plus populaires',
	'most_loss_logs' => 'Logs avec le plus grand nombre de pertes',
	'most_rating_logs' => 'Best rating weekly logs',
	'last' => 'Derniers',
	'public_logs' => 'Logs publiques',
	'missle_launch_det' => 'Lancement de missiles detectes',
	'defense' => 'Defense',
	'fleet' => 'Flotte',
	'exp_real_lossed' => 'Pertes reelles',
	'wm_donate' => 'Faites un don pour supporterle projet',
	'forgot_password' => 'Forgot Password?',
	'registration' => 'Registration',
	'login' => 'Login',
	'remember_me' => 'Remember me',
	'fix_list' => 'Fix list',
	'thanks' => 'Thanks',
	'uploaded' => 'Uploaded in 24h:',
	'total_uploaded' => 'Total uploaded:',
	'search' => 'Search',
	'r_users' => 'Users:',
	'option' => 'Option',
	'setting' => 'Setting',
	'set' => 'Set',
	'default' => 'Default',
	'user_comments_title' => 'USER COMMENTS',
	'index_pagegen' => 'Page générée en',
	'index_pagegensec' => 'secondes',
	'com_scpatk' => 'scrap Angreifer',
	'com_scpdef' => 'scrap Defender',
	'acc_list' => 'Liste des grumes',
	'acc_oldlist' => 'Liste des anciens journaux',
	'acc_spyrpt' => 'rapports despions',
	'acc_allog' => 'tous les journaux',
	'page_up' => 'en haut',
	'uni_features' => 'Universes features',

	'eco' => 'Eco',
	'fleet' => 'Fleet',
	'size' => 'Size',
	'sab' => 'ACB',
	'debris' => 'Debris',
	'ovo' => 'DiDF',
	'top' => 'Top',
	'gamers' => 'Accounts',
	'online' => 'Online',
	'fields' => 'Fields',
	'circular_gal' => 'Circ&#x202F;Galaxies',
	'circular_sys' => 'Circ&#x202F;Systems',
	'probe' => 'Probe',
	'opening_date' => 'Opening&#x202F;date',

	'esp_rep_from' => 'Espionage report from',
	'player' => 'Player',
	'chance_esp' => 'Chance of counter-espionage',
	'unable_info_esp' => 'We were unable to retrieve any reliable information of this type from the scan.',
	'activity_esp_0' => 'Your espionage does not show abnormalities in the atmosphere of the planet. There appears to have been no activity on the planet within the last hour.',
	'activity_esp_1' => 'Your espionage report shows abnormalities in the atmosphere of the planet which suggests activity within the last <font color=\'red\'>%min%</font> minutes.',

	'resources' => 'Resources',
	'fleets' => 'Fleets',
	'defence' => 'Defence',
	'building' => 'Building',
	'research' => 'Research',	
);
